### ISSUE TITLE
4800u可以吗

### ISSUE THREAD

**Issue by ASguoyue** [Zrc00/Lenovo-Xiaoxin-15ARE-Hackintosh#1]
可以进行黑苹果吗

**Comment by Zrc00** [comment]
可以的，我就是这个，EFI文件会抽空发
非常抱歉，现在才看到
________________________________
发件人: ASguoyue ***@***.***>
发送时间: Thursday, June 29, 2023 9:42:40 PM
收件人: Zrc00/Lenovo-Xiaoxin-15ARE-Hackintosh ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Zrc00/Lenovo-Xiaoxin-15ARE-Hackintosh] 4800u可以吗 (Issue #1)


可以进行黑苹果吗

―

**Comment by Zrc00** [comment]
可以的，我就是这个配置，EFI会抽空发，我会随附安装的注意事项，敬请期待。

**Comment by Watish** [comment]
相关acpi是否通用，我在另一台小新上一直遇到acpi相关的kernel panic
