### ISSUE TITLE
Bug解决

### ISSUE THREAD

**Issue by Zrc00** [Zrc00/Lenovo-Xiaoxin-15ARE-Hackintosh#2]
我这个EFI有Bug，只能用Big Sur，12以上系统安装都进不去，有解决方法吗？

**Comment by Watish** [comment]
我是小新air14-ARE，可以参考该仓库
https://github.com/zabdottler/Lenovo-Yoga-16S-hackintosh
我用的此仓库EFI，已知问题：无法睡眠和麦克风不能用以及核显解码有时异常外
亲测 monterey和ventura都没有问题

**Comment by Zrc00** [comment]
我试试，感谢

**Comment by Zrc00** [comment]
已解决
